server:
  port: 8082

spring:
  application:
    name: warehouse-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: inventory-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5440/pharmacy_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true